language: android
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install:
  - git pull -X theirs --no-edit https://github.com/larsgrefer/android-module-travis-helper.git
  - git submodule init
  - git submodule update
script:
  - ./gradlew -b travis.gradle build check
