language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - android-7
  - extra
script:
- "./gradlew build check"
after_success:
- if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]
  ; then ./gradlew --stacktrace uploadArchives ; fi
deploy:
  provider: releases
  api_key:
    secure: V35m6Mzyieg5jMI6OJo4fi4DjpuxxZ2JTj2E8xAPjAWerymccc4Qlp6bLUgTLU19oQI2ADOEgawqP/sGPpHST+rM0ypXiEKNo2UnK+Pt7oan7Q1j3jVKs5ts8wwlPlA7EJW1Pguryyc+Zq0XybYq9tcgjb7LfxVkFZD7EpiK/9Y=
  file:
    - android-library-base/build/outputs/aar/android-library-base-release.aar
    - android-library-mvvm/build/outputs/aar/android-library-mvvm-release.aar
    - android-library-orm/build/outputs/aar/android-library-orm-release.aar
  skip_cleanup: true
  on:
    repo: larsgrefer/android-library
    tags: true
