language: android
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
android:
  components:
    - build-tools-21.1.2
    - android-21
    - android-7
    - extra
script:
  - ./gradlew --info build check
