language: android
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
android:
  components:
    - build-tools-21.1.2
    - android-21
    - android-7
    - extra
install:
  - git config user.name "Travis CI"
  - git config user.email "travis@ci.example"
  - git pull -X theirs --no-commit --no-edit https://github.com/larsgrefer/android-module-travis-helper.git
script:
  - ./gradlew --info build check
