language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra
script: "./gradlew build check"

deploy:
  provider: releases
  api_key:
    secure: V35m6Mzyieg5jMI6OJo4fi4DjpuxxZ2JTj2E8xAPjAWerymccc4Qlp6bLUgTLU19oQI2ADOEgawqP/sGPpHST+rM0ypXiEKNo2UnK+Pt7oan7Q1j3jVKs5ts8wwlPlA7EJW1Pguryyc+Zq0XybYq9tcgjb7LfxVkFZD7EpiK/9Y=
  file:
    - appcompat-preference/build/outputs/aar/appcompat-preference-release.aar
    - playground/build/outputs/aar/playground-release.aar
    - util/build/outputs/aar/util-release.aar
    - injection/build/outputs/aar/injection-release.aar
    - mvvm/build/outputs/aar/mvvm-release.aar
    - orm/build/outputs/aar/orm-release.aar
    - material-colors/build/outputs/aar/material-colors.aar
    - holo-colors/build/outputs/aar/holo-colors.aar
  skip_cleanup: true
  on:
    repo: freefair/android-library
    tags: true
