language: android
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
android:
  components:
    - build-tools-22.0.1
    - android-22
    - android-7
    - extra
script:
  - ./gradlew --info build check
after_success:
- if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] ; then ./gradlew uploadArchives ; fi

